Merge MSAL React Native Proof of Concept Library and Sample
AzureAD/microsoft-authentication-library-for-js pull request #1910
Opened 2020-07-07 21:32 UTC by ahnmelis

This merge will add MSAL for React Native Proof of Concept (Android) to the lib folder as well as the corresponding sample app to the samples folder. 
Important files:
* `MSALModule.java` - this file is key to the library. It contains React functions written in Java that wrap MSAL Android's `ISingleAccountPublicClientApplication` methods. Each of the methods return a promise, which allows data to be "bridged" over to the React Native side. 
* `App.js` - the main sample app file. It imports the library as `MSAL` and demonstrates how each of the methods could be used. For `acquireTokenSilent` and `acquireToken`, the received access token is used to make a call to Microsoft Graph's API. The UI and functionality was designed to match MSAL Android's sample app (but blue). 
* `auth_config_single_account.json` - the library is written such that the config file needs to be put in res/raw of the sample app. While this matches [MSAL Android's suggestion](https://github.com/AzureAD/microsoft-authentication-library-for-android#step-2-create-your-msal-configuration-file) and is alright in this context (only supporting Android and not iOS), I've been recently wondering if there's a good way to have only one config file that both platforms can access. Unfortunately, I'm not familiar enough with iOS dev to see how this could work, but I think it's definitely something to consider if MSAL React Native is developed in the future. 
* README.md for the library and sample app - feedback is especially appreciated for these files. They are first drafts!

2020-07-09 23:48 UTC, jo-arroyo commented on lib/msal-react-native-android-poc/README.md
> +* compatibility with iOS
```suggestion
* Compatibility with iOS
```

2020-07-09 23:48 UTC, jo-arroyo commented on lib/msal-react-native-android-poc/README.md
> +* compatibility with the Android platform
```suggestion
* Compatibility with the Android platform
```

2020-07-09 23:48 UTC, jo-arroyo commented on lib/msal-react-native-android-poc/README.md
> +* authenticating users with work and school Azure AD accounts (AAD)
```suggestion
* Authenticating users with work and school Azure AD accounts (AAD)
```

2020-07-09 23:48 UTC, jo-arroyo commented on samples/msal-react-native-android-poc-sample/App.js
> +    try{
```suggestion
    try {
```

2020-07-09 23:48 UTC, jo-arroyo commented on samples/msal-react-native-android-poc-sample/App.js
> +    try{
```suggestion
    try {
```

2020-07-09 23:49 UTC, jo-arroyo commented on lib/msal-react-native-android-poc/README.md
> +isSharedDevice() | returns a boolean that corresponds to whether the current device is shared or not.
Just a few nitpicks!

2020-07-10 00:01 UTC, jo-arroyo approved these changes

2020-07-10 17:48 UTC, tnorling requested changes
Really nice job! Just a few comments around utilizing Constants more

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/README.md
> +Additionally, with this library being a proof of concept, it is not recommended to be used for React Native applications intended for production.
I think this is an important point that could be bolded and moved to the top of this Readme

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/README.md
> +* B2C or AD FS
```suggestion
* B2C or ADFS
```

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +        return "MSAL";
Move "MSAL" to constants file and reference here

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +            String[] array = {"User.Read"};
Reference your `DEFAULT_SCOPES` constant here

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +            String[] array = {"User.Read"};
`DEFAULT_SCOPES`

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +            String[] array = {"User.Read"};
`DEFAULT_SCOPES`

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +        map.putMap("account", mapAccount(result.getAccount()));
All these keys can be added to the Constants file

2020-07-10 17:48 UTC, tnorling commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +        map.putString("authority", account.getAuthority());
Here too

2020-07-10 18:28 UTC, jmckennon commented on lib/msal-react-native-android-poc/README.md
> +Additionally, with this library being a proof of concept, it is not recommended to be used for React Native applications intended for production.
+1

2020-07-10 18:28 UTC, jmckennon commented on lib/msal-react-native-android-poc/README.md
> +signIn(String scopesValue) | Directs a user to sign in with an AAD account. scopesValue is a String containing scopes separated by spaces (" "). Returns a map with the `authority`, `id`, `tenantId`,
Not the biggest deal, but this table could definitely be cleaned up for readability in the markdown

2020-07-10 18:28 UTC, jmckennon commented on lib/msal-react-native-android-poc/README.md
> +    var account = await MSAL.signIn(scopesValue);
I may just be ignorant of how react-native works under the hood, but is there a reason why all of these `var` can't be `const` or `let`?

2020-07-10 18:32 UTC, pkanher617 commented on lib/msal-react-native-android-poc/README.md
> +Additionally, with this library being a proof of concept, it is not recommended to be used for React Native applications intended for production.
+1

2020-07-10 20:14 UTC, ahnmelis commented on lib/msal-react-native-android-poc/README.md
> +    var account = await MSAL.signIn(scopesValue);
No good reason for `var`. I just read an article about when to use all three and concluded that pretty much all of them should be replaced with `const`. Thanks for pointing this out.

2020-07-10 20:55 UTC, ahnmelis commented on lib/msal-react-native-android-poc/README.md
> +Additionally, with this library being a proof of concept, it is not recommended to be used for React Native applications intended for production.
Done!

2020-07-10 20:57 UTC, ahnmelis commented on lib/msal-react-native-android-poc/README.md
> +signIn(String scopesValue) | Directs a user to sign in with an AAD account. scopesValue is a String containing scopes separated by spaces (" "). Returns a map with the `authority`, `id`, `tenantId`,
added some spacing to hopefully improve readability.

2020-07-10 21:33 UTC, ahnmelis commented on lib/msal-react-native-android-poc/android/src/main/java/com/reactlibrary/MSALModule.java
> +        return "MSAL";
This, and all of the map keys are now in the constants file. All of the constants are utilized in the sample app now.

2020-07-10 22:52 UTC, hectormmg approved these changes
A couple suggestions, otherwise, LGTM!

2020-07-10 22:52 UTC, technical-boy commented on samples/msal-react-native-android-poc-sample/App.js
> +    return (
The render method is a little on the long side. It's definitely not a priority but a possible improvement would be to refactor some of the UI portions out into different components. For example, putting the `View` containing all the action (i.e. Get Graph Data Silently) buttons in a separate component (with it's own stylesheet) could drastically improve the readability of the App component.

2020-07-10 22:53 UTC, jasonnutter commented on .vscode/settings.json
> +    },
I actually would like this one to be kept, e.g. for lint.

2020-07-10 23:53 UTC, jasonnutter approved these changes

2020-07-11 00:57 UTC, tnorling approved these changes

2020-07-13 18:23 UTC, ahnmelis commented on samples/msal-react-native-android-poc-sample/App.js
> +    return (
splitting up the render method makes sense, but while trying to create a new component for the buttons, i've ran into some questions.
The buttons and other objects in my app all depend and modify state variables, so splitting the buttons off as a separate component would mean that they wouldn't have access to modifying and getting updates from the state variables without creating more functions that "lift" the state up (and bring the state down). 
I was wondering what your thoughts were about these potential trade offs... for sure the current render function is way too long and would be improved stylistically with separate components, but I wonder if the added functions and logic with lifting state would also make my relatively small app complicated to read as well.

2020-07-16 18:21 UTC, sameerag commented on lib/msal-react-native-android-poc/README.md
> +* MacOS: `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64`
We don't support linux?

2020-07-16 18:31 UTC, ahnmelis commented on lib/msal-react-native-android-poc/README.md
> +* MacOS: `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64`
Didn't see an option for Linux in the MSAL faq or Azure portal, but I wonder if it's the same as Windows: https://stackoverflow.com/questions/33073463/generating-release-key-hash-in-linux-osubuntu-android-facebook-sdk

2020-07-16 18:35 UTC, sameerag commented on lib/msal-react-native-android-poc/README.md
> +* MacOS: `keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64`
Sounds good

2020-07-16 21:16 UTC, merged