ClientAssertion.parseCertificate - handle newlines
AzureAD/microsoft-authentication-library-for-js pull request #2721
Opened 2020-12-09 02:37 UTC by eanders-MS

It is common for certs exported from pfx to contain newlines. For example, OpenSSL exports certs in the format:
```
-----BEGIN CERTIFICATE-----
MIIFSDCCBDCg........................................
IqNDl5bnkmR0........................................
eUd4y23epjUW........................................
BnozMiiGCHuG........................................
jGqq8qpdA6wT........................................
...
-----END CERTIFICATE-----
```

The regex in `ClientAssertion.parseCertificate` was unable to parse such certs due to the `.` term's default behavior of not matching newlines (even when the multiline flag is present). This is fixed by the addition of the s (dotall) flag.

Fixes https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2720

2020-12-09 16:42 UTC, jasonnutter commented
@eanders-MS Please generate a beachball changelog file. This can be done by navigating to the root of the repo, running `npm install`, then running `npm run beachball:change`. You will want to select `prerelease`, thanks!

2020-12-09 17:34 UTC, eanders-MS commented
Looks like my changes to the unit test are failing. How do I run them locally? I was hoping it would succeed in CI, but that didn't happen.

2020-12-09 19:41 UTC, jmckennon requested changes
Looks good to me, nice catch on this functionality. We appreciate the help with the fix. Will approve after the PR number is added to the changelog file.

2020-12-09 19:41 UTC, jmckennon commented on change/@azure-msal-node-e1216fab-db96-4b5e-b319-17f3bcffa13b.json
> +  "comment": "ClientAssertion.parseCertificate - allow newlines in cert",
```suggestion
  "comment": "ClientAssertion.parseCertificate - allow newlines in cert (#2721).",
```

This adds in the PR number to the changelog as well.

2020-12-09 21:35 UTC, tnorling approved these changes

2020-12-10 01:00 UTC, jasonnutter approved these changes
Thanks for the fix!

2020-12-10 18:23 UTC, jmckennon approved these changes

2020-12-11 20:27 UTC, merged