Block nested popups
AzureAD/microsoft-authentication-library-for-js pull request #3249
Opened 2021-03-19 18:49 UTC by tnorling

When the page used as the `redirectUri` invokes `loginPopup` on page load it can sometimes open another popup that never resolves. This PR adds a check to the `preflightBrowserEnvironmentCheck` to see if it's already in a popup and blocks subsequent requests. 

Fixes #3160

2021-03-19 18:50 UTC, tnorling commented
@jasonnutter Is this going to break any valid use cases @pkanher617 and I didn't consider?

2021-03-22 23:54 UTC, jasonnutter commented on lib/msal-browser/src/utils/BrowserUtils.ts
> +        if (window.opener && window.opener !== window) {
Two things:

1. I think you should pass in the interaction type, and only make this check if a popup request is being made, as redirect operations inside a popup should be allowed.
2. Make sure this test does result positives. Just beacuse a window has an opener doesnt mean its a popup.

2021-03-22 23:57 UTC, jasonnutter commented on lib/msal-browser/src/utils/BrowserUtils.ts
> +        if (window.opener && window.opener !== window) {
Yeah, this check caused problems in v1, and was part of the reason we put the interaction type in the state value. See https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1413

2021-03-22 23:58 UTC, jasonnutter requested changes
Please find a more reliable check for popups, and ensure this only blocks popup requests.

2021-03-23 00:30 UTC, jasonnutter commented on lib/msal-browser/src/utils/BrowserUtils.ts
> +        if (window.opener && window.opener !== window && window.name.indexOf(`${BrowserConstants.POPUP_NAME_PREFIX}.`) === 0) {
Might be good to check truthiness of `window.name` to be safe.
```suggestion
        if (window.opener && window.opener !== window && typeof window.name === "string" && window.name.indexOf(`${BrowserConstants.POPUP_NAME_PREFIX}.`) === 0) {
```

2021-03-24 20:21 UTC, jasonnutter approved these changes

2021-03-24 21:29 UTC, pkanher617 approved these changes

2021-03-24 21:45 UTC, merged