Fix node e2e tests
AzureAD/microsoft-authentication-library-for-js pull request #3369
Opened 2021-03-31 22:25 UTC by hectormmg

This PR increases the timeout limit in the Auth Code E2E tests for msal-node since they are failing intermittently on the CI pipeline.

2021-04-01 09:59 UTC, samuelkubai approved these changes

2021-04-01 10:02 UTC, samuelkubai requested changes
The tests seem to be failing in an inconsistent way, are these timeouts enough to clear the errors?

2021-04-20 16:42 UTC, jasonnutter approved these changes

2021-04-26 10:21 UTC, samuelkubai approved these changes

2021-04-27 16:40 UTC, merged