[msal-browser] Fix hash removal from URL and browser history after interactive request
AzureAD/microsoft-authentication-library-for-js pull request #3609
Opened 2021-05-08 00:08 UTC by hectormmg

This PR:

- Refactors `BrowserUtils.clearHash` to accept a window as a parameter and perform hash removal/history replacement on that content window.
- Fixes a bug in which the auth code hash was being left in the browser history

2021-05-10 15:30 UTC, jasonnutter approved these changes

2021-05-10 16:16 UTC, tnorling approved these changes

2021-05-11 23:04 UTC, jo-arroyo approved these changes

2021-05-12 00:14 UTC, jasonnutter requested changes
Marking as requesting changes until updates are pushed.

2021-05-12 00:57 UTC, hectormmg commented
@jasonnutter should be gtm now, sorry

2021-05-12 01:19 UTC, hectormmg commented on lib/msal-angular/src/msal.navigation.client.ts
> +        if (options.noHistory) {
```suggestion
        // Prevent hash clearing from causing an issue with Client-side navigation after redirect is handled
        if (options.noHistory) {
```

2021-05-12 01:20 UTC, hectormmg commented on lib/msal-angular/src/msal.navigation.client.ts
> +        if (options.noHistory) {
@jasonnutter is this accurate?

2021-05-12 03:22 UTC, jasonnutter approved these changes

2021-05-12 15:17 UTC, merged

2022-03-24 12:42 UTC, MaartenX commented
I noticed an extra history entry since this change; The following code is now always executed, even if ```replaceState``` exists:

``` javascript
contentWindow.location.hash = Constants.EMPTY_STRING;
```

Shouldn't the code above only be executed when ```replaceState``` does not exist?

2022-05-09 06:14 UTC, WellyHong commented
As @MaartenX  mention above, I also encounter the unexpected behavior after login, it redirect to the default page even if I set `navigateToLoginRequestUrl: false`.