[msal-node]: Increase code coverage
AzureAD/microsoft-authentication-library-for-js pull request #3975
Opened 2021-08-17 09:08 UTC by samuelkubai

Increase code coverage of the msal-node library to +90%

2021-08-17 16:30 UTC, jasonnutter commented on lib/msal-node/test/client/ConfidentialClientApplication.spec.ts
> +    test.only('acquireTokenByClientCredential handles AuthErrors as expected', async () => {
```suggestion
    test('acquireTokenByClientCredential handles AuthErrors as expected', async () => {
```

2021-08-25 16:52 UTC, jasonnutter commented on lib/msal-node/test/client/ConfidentialClientApplication.spec.ts
> +    test.only('acquireTokenByClientCredential handles AuthErrors as expected', async () => {
@samuelkubai FYI

2021-09-07 22:15 UTC, jasonnutter requested changes
Need to remove exclusive test.

2021-09-27 06:42 UTC, sameerag commented
@samuelkubai any update on this?

2021-09-27 07:38 UTC, samuelkubai commented
> @samuelkubai any update on this?

Hi @sameerag, working on this, this week whilst on call.

2021-09-30 22:53 UTC, jasonnutter approved these changes

2021-10-04 20:51 UTC, hectormmg approved these changes

2021-10-04 21:51 UTC, merged