fix: Object.keys might return false result
AzureAD/microsoft-authentication-library-for-js pull request #4380
Opened 2022-01-10 10:38 UTC by Bartheleway

When window storage is being proxied key might not be enumerable anymore. Safe way is to use key() which returns the n-th key of the storage.

This intends to fix #4379.

I did test modifying directly the code into the compiled source and report that it is working as expected.

2022-01-10 15:58 UTC, jasonnutter requested changes
Thanks for filing this PR. Please include the following:

1. A test demonstrating the fix.
2. A comment in the file explaining why this change was made.
3. Change file, created by running npm run beachball:change in the root of the repo.

Thanks!

2022-01-10 16:12 UTC, Bartheleway commented
Hi, thanks for reviewing this quickly

1. I will try to make a test, not sure how I can setup the storageProxy in test as it is code written by Salesforce developers. Do you also want a test that shows that previous version and new works the same when no proxy ?
2. I don't get what you want, the commit message is describing the change and that is the correct place for explaining changes. Code comment should only clarify functionality not change. Do you agree ?
3. Ok, I missed that point, will do

2022-01-10 19:05 UTC, jasonnutter commented
> 1. I will try to make a test, not sure how I can setup the storageProxy in test as it is code written by Salesforce developers. Do you also want a test that shows that previous version and new works the same when no proxy ?

A test that shows when `window.localStorage` and `window.sessionStorage`  are not enumerable, that relevant APIs still work.

> 2. I don't get what you want, the commit message is describing the change and that is the correct place for explaining changes. Code comment should only clarify functionality not change. Do you agree ?

I disagree. Comments can be used to detail why a piece of code exists or is written in a certain way, in addition to in the commit message.

> 3. Ok, I missed that point, will do

Thanks!

2022-01-10 19:06 UTC, jasonnutter commented on lib/msal-browser/src/cache/BrowserStorage.ts
> +        for (let i = 0; i < this.windowStorage.length; ++i) {
```suggestion
        // Manually iterate to properly support environments where localStorage/sessionStorage are not enumerable, e.g. Salesforce
        for (let i = 0; i < this.windowStorage.length; ++i) {
```

2022-03-28 15:00 UTC, ghost commented
Reminder: The next release is scheduled for next week and this PR appears to be stale :( 

If changes have been requested please address feedback. 
If this PR is still a work in progress please mark as draft.

2022-04-04 21:46 UTC, jasonnutter commented
Closing, per comment in #4379 to not include for unsupport environments that are not following standards.

2022-04-04 21:46 UTC, closed without merging