Typo [QuickFix] - PopupClient.ts
AzureAD/microsoft-authentication-library-for-js pull request #4385
Opened 2022-01-11 17:04 UTC by ordonezgs

Fixing up a Typo of a logger message.

2022-01-12 21:02 UTC, jasonnutter commented
> Thank you for your contribution! Please generate change files by running `npm run beachball:change` from the root of the repo, then answer each prompt and push up the generated files.

@ordonezgs Please see message above to generate and commit changefiles, thanks!

2022-01-12 21:02 UTC, jasonnutter requested changes
Changefile needed, otherwise looks good.

2022-01-14 01:07 UTC, ordonezgs commented
Done,

Thank you very much, I have already run the above command and generated the corresponding file.

Please let me know of any further requirements.

Thank you very much @jasonnutter .

2022-01-14 17:43 UTC, ordonezgs reviewed
Changefile added. Beachball check done.

2022-01-14 17:50 UTC, tnorling commented on change/@azure-msal-browser-c15c8f41-0fa0-4619-82ff-20addba77243.json
> +  },
```suggestion
  "comment": "Fix typo in logger message #4385",
```

2022-01-14 18:38 UTC, ordonezgs commented on change/@azure-msal-browser-c15c8f41-0fa0-4619-82ff-20addba77243.json
> +  },
Done, thanks.

2022-01-14 19:16 UTC, tnorling approved these changes

2022-01-20 07:27 UTC, sameerag approved these changes

2022-01-20 16:57 UTC, merged