Added nonce to msal node
AzureAD/microsoft-authentication-library-for-js pull request #4443
Opened 2022-01-25 09:12 UTC by mpminayo

Added nonce feature.

2022-01-25 17:13 UTC, jasonnutter commented on samples/msal-node-samples/auth-code/test/auth-code-aad.spec.ts
> +        // });
Should these tests be uncommented?

2022-01-25 17:14 UTC, jasonnutter commented on change/@azure-msal-node-55903946-5aa6-4aec-83a3-b359a9269131.json
> +  "comment": "Added nonce to msal node",
```suggestion
  "comment": "Added nonce to msal node #4443",
```

2022-01-27 00:17 UTC, jasonnutter commented on samples/msal-node-samples/auth-code/package.json
> +    "express-session": "^1.17.2",
This should be in the regular `dependencies` list, given its necessary for the app at runtime.

2022-01-27 09:41 UTC, sameerag commented on samples/msal-node-samples/auth-code/index.js
> +        const authCodeResponse = { nonce :req.session.nonce }
Can we please add documentation links to `nonce` in the standard and in the repo?

2022-01-28 22:23 UTC, jasonnutter requested changes
A couple comments, looks good otherwise! Any unit tests we can add?

2022-01-28 22:24 UTC, jasonnutter commented on samples/msal-node-samples/auth-code/test/auth-code-aad.spec.js
> +"use strict";
This looks like a generated file, which shoudn't be committed.

2022-02-08 14:50 UTC, closed without merging