Angular13 RxJS 6/7 Sample Apps
AzureAD/microsoft-authentication-library-for-js pull request #4605
Opened 2022-03-15 21:10 UTC by Robbie-Microsoft

2022-03-15 22:56 UTC, jasonnutter requested changes
Tested locally and this looks good, thanks! I've push up one commit to remove the `package-lock` files. 

Please complete the following:

1. Generate change file (can mark as minor change)
2. Add both of these samples to the e2e tests (@jo-arroyo can help you get that running)
3. Add `13` as supported verison in the supported version table in the MSAL Angular README
4. As fast follow up to this PR, start another PR to add an Angular 14 sample.

2022-03-15 23:59 UTC, jo-arroyo requested changes
Also tested locally. Great work! A few more changes would be nice:

1. Update the READMEs for each sample, cf. Angular 10 sample. 
2. Update the README for the `msal-angular-v2-samples` folder. This is where we list the differences between the samples. Feel free to include an explanation for why we have a RxJS 6 and RxJS 7 sample.
3. Update the MSAL Angular README to include links to angular13 samples.
4. Remove the `.vscode` and `assets` folders for each sample. 

I will reach out to you offline about the e2e tests.

2022-03-16 21:29 UTC, Robbie-Microsoft commented
>

2022-03-23 20:44 UTC, jasonnutter commented on change/@azure-msal-angular-8f602981-ceaf-457b-9710-7afdfeb9fcae.json
> +  "comment": "Created two Angular13 sample apps. One uses RxJS v6 and the other uses RxJS v7.",
```suggestion
  "comment": "Add support for rxjs v7 and Angular 13 #4605",
```

2022-03-29 22:42 UTC, jasonnutter commented
@Robbie-Microsoft E2E tests are passing. It required that I add `compilerOptions.paths` entries for Angular to both samples (which do in the other samples), and for rxjs for the rxjs7 sample. Example:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/94f17e2d9529343a2d0c543dbd2376b5f2ec75c9/samples/msal-angular-v2-samples/angular13-rxjs7-sample-app/tsconfig.json#L25-L28

It would probably be good to call this out for each sample.

2022-03-30 16:51 UTC, jasonnutter approved these changes
Looks good, thanks for putting this together!

2022-03-30 18:30 UTC, jo-arroyo requested changes
A few changes, thanks!

2022-03-30 18:30 UTC, jo-arroyo commented on samples/msal-angular-v2-samples/angular13-rxjs7-sample-app/README.md
> +# Angular13RxJS7SampleApp
Can you update these samples to have a similar README with as other msal-angular samples? See here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-sample-app

2022-03-30 18:30 UTC, jo-arroyo commented on samples/msal-angular-v2-samples/angular13-rxjs6-sample-app/README.md
> +# Angular13RxJS6SampleApp
Requesting readme change here to align with other msal-angular sample readmes: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-sample-app

2022-03-30 18:30 UTC, jo-arroyo commented on samples/msal-angular-v2-samples/angular13-rxjs7-sample-app/jest.config.js
> +        __PORT__: 4208,
Change to unique ports (different to other msal-angular samples).

2022-03-30 18:30 UTC, jo-arroyo commented on samples/msal-angular-v2-samples/angular13-rxjs6-sample-app/jest.config.js
> +        __PORT__: 4208,
Change to unique ports (different to other msal-angular samples).

2022-03-30 19:13 UTC, jo-arroyo approved these changes
Looks great! Thanks for all your good work!

2022-03-30 19:28 UTC, merged