fixed files violating max-len lint rule
AzureAD/microsoft-authentication-library-for-js pull request #5136
Opened 2022-08-26 20:28 UTC by lalimasharda

2022-08-26 22:02 UTC, hectormmg requested changes

2022-08-26 22:02 UTC, hectormmg commented on change/@azure-msal-node-extensions-2f3c9951-5c33-4e4b-986a-789661c24467.json
> +  "email": "email not defined",
```suggestion
  "email": "lalimasharda@microsoft.com",
```

2022-08-26 22:03 UTC, hectormmg commented on change/@azure-msal-node-extensions-2f3c9951-5c33-4e4b-986a-789661c24467.json
> +  "comment": "Fixing files to follow max-len rule",
```suggestion
  "comment": "Fixing files to follow max-len rule #5136",
```

2022-08-29 08:55 UTC, bmahall approved these changes

2022-08-29 17:26 UTC, hectormmg approved these changes
LGTM

2022-08-29 18:48 UTC, merged