May Alpha 2 Release
AzureAD/microsoft-authentication-library-for-js pull request #6025
Opened 2023-05-16 23:07 UTC by hectormmg

This PR bumps pre-release versions for:
- `msal-browser`
- `msal-node`
- `msal-angular`
- `msal-react`

Also removes stray node-token-validation changefiles

2023-05-16 23:09 UTC, tnorling approved these changes

2023-05-16 23:31 UTC, peterzenz approved these changes

2023-05-17 13:20 UTC, konstantin-msft approved these changes

2023-05-17 13:20 UTC, konstantin-msft approved these changes

2023-05-17 13:40 UTC, Analynn24 requested changes
```

```

2023-05-17 16:59 UTC, merged