Fix: Cached AccessToken missing realm property in OIDC scenario
AzureAD/microsoft-authentication-library-for-js pull request #6689
Opened 2023-11-11 21:26 UTC by bbush915

In the case an application is using a separate OIDC-compliant authority and the tid claim is empty, the cached access token does not contain a realm property. One side-effect is that the cached access token will fail the isAccessTokenEntity check, preventing it from being re-used.

2023-11-14 21:25 UTC, tnorling commented on lib/msal-common/src/response/ResponseHandler.ts
> +                    Constants.EMPTY_STRING,
```suggestion
                idTokenClaims?.tid ||
                    authority.tenant ||
                    "",
```

2023-11-14 21:26 UTC, tnorling requested changes
Thanks for the PR! Can you please add a test & generate changefiles by running `npm run beachball:change` from the root of the repo.

2023-11-14 23:03 UTC, bbush915 commented
@microsoft-github-policy-service agree [company="Dialexa, an IBM Company"]

2023-11-14 23:03 UTC, bbush915 commented
@microsoft-github-policy-service agree company="Dialexa, an IBM Company"

2023-11-14 23:05 UTC, bbush915 commented on lib/msal-common/src/response/ResponseHandler.ts
> +                    Constants.EMPTY_STRING,
Updated!

2023-11-14 23:07 UTC, bbush915 commented
@tnorling addressed comment and added a test. The beachball command reported no change files are needed.

2023-11-15 00:09 UTC, tnorling commented
> @tnorling addressed comment and added a test. The beachball command reported no change files are needed.

Ah I suspect this is because your feature branch is also called dev. Can you try another branch?

2023-11-15 01:53 UTC, bbush915 commented
> > @tnorling addressed comment and added a test. The beachball command reported no change files are needed.
> 
> Ah I suspect this is because your feature branch is also called dev. Can you try another branch?

Good call! Sorry for the messy commits, but I got the change files in place!

2023-11-15 18:48 UTC, tnorling approved these changes

2023-12-19 17:38 UTC, bbush915 commented
@tnorling Hello! Is there anything I can do to help this land?

2023-12-19 18:03 UTC, sameerag commented
@bbush915 I can help land this. Looks like some tests are failing.

2024-01-02 15:03 UTC, bbush915 commented
@sameerag I validated that tests are all passing locally. Is there anything I can do to troubleshoot the failing E2E tests? It looks like they are all reporting: `Git fetch failed with exit code: 128`

2024-01-08 17:10 UTC, bbush915 commented
@tnorling @sameerag following up on the above, I'm not sure why the E2E tests are failing, but can do what is needed to assist. Hoping to get this to land soon, since it is blocking some upgrades.

2024-01-11 01:04 UTC, BboyAkers commented
Hey cool and awesome former co-workers 🙂! Can this get approved and merged? It's blocking a couple companies and their clients including one I'm working with 😅

2024-01-29 07:53 UTC, sameerag approved these changes

2024-01-29 07:54 UTC, sameerag commented
> Hey cool and awesome former colleagues 🙂! Can this get approved and merged? It's blocking a couple companies and their clients including one I'm helping with 😅🙏🏾. So sorry, for the push and hope I don't come off as rude!

Approved and updated the base branch. Hopefully tests pass now.

2024-01-29 16:38 UTC, BboyAkers commented
> > Hey cool and awesome former colleagues 🙂! Can this get approved and merged? It's blocking a couple companies and their clients including one I'm helping with 😅🙏🏾. So sorry, for the push and hope I don't come off as rude!
> 
> Approved and updated the base branch. Hopefully tests pass now.

[![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/11778717/158cf409-ccca-4669-ae9a-d5aa5d4565fb)](https://media.tenor.co/images/3ed84016385a06560957920423fea2f8/raw) 😭 🙏🏾 ❤️

2024-01-29 17:03 UTC, merged